version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - backend_db:/app/db_volume
    environment:
      - DATABASE_URL=sqlite:///app/db_volume/liquidaciones.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend_db:
